[testlib] Make GPU burn test a library test
reframe-hpc/reframe pull request #2503
Opened 2022-05-08 11:52 UTC by vkarak

More particularly, this PR offers the following:

- Converts the GPU burn test into a library test.
- Bases the the CSCS test on this new library test.
- Introduces a new source file organisation for the GPU microbenchmarks (currently, only the GPU burn test follows the new structure, but the rest of the tests will have to follow it as soon as they are updated).
- The CSCS config is updated with metadata on its partitions and environments.
- A new convenience method is added to the `SystemPartition` that allows to select the devices of a certain type.

2022-05-08 11:53 UTC, pep8speaks commented
Hello @vkarak, Thank you for submitting the Pull Request!





* In the file [`hpctestlib/microbenchmarks/gpu/gpu_burn.py`](https://github.com/eth-cscs/reframe/blob/d4874bf496a7a7900e5cb3ef1bbd1ea334fe57d9/hpctestlib/microbenchmarks/gpu/gpu_burn.py):

> [Line 104:80](https://github.com/eth-cscs/reframe/blob/d4874bf496a7a7900e5cb3ef1bbd1ea334fe57d9/hpctestlib/microbenchmarks/gpu/gpu_burn.py#L104): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)



Do see the ReFrame [Coding Style Guide](https://github.com/eth-cscs/reframe/wiki/coding-style-guide)

2022-05-09 13:01 UTC, rsarm commented on config/cscs.py
> +                    'environs': ['gnu', 'rcom'],
```suggestion
                    'environs': ['gnu', 'rocm'],
```

2022-05-11 11:54 UTC, rsarm approved these changes

2022-05-11 14:41 UTC, teojgo requested changes

2022-05-11 14:41 UTC, teojgo commented on hpctestlib/microbenchmarks/gpu/gpu_burn.py
> +    on a selected set of GPUs on the node that it runs.
```suggestion
    on a selected set of GPUs of the node on which it executes.
```

2022-05-11 14:41 UTC, teojgo commented on hpctestlib/microbenchmarks/gpu/gpu_burn.py
> +    This benchmark does sets the
```suggestion
    This benchmark sets the
```

2022-05-11 14:41 UTC, teojgo commented on hpctestlib/microbenchmarks/gpu/gpu_burn.py
> +    attribute, if not already set, based on the number devices with ``type ==
```suggestion
    attribute, if not already set, based on the number of devices with ``type ==
```

2022-05-11 15:05 UTC, vkarak commented on hpctestlib/microbenchmarks/gpu/gpu_burn.py
> +    on a selected set of GPUs on the node that it runs.
I rephrased it a bit differently.

2022-05-11 15:17 UTC, teojgo approved these changes

2022-05-12 07:48 UTC, merged