[bugfix] Reset poll rate every time a test finishes the compilation or run phase
reframe-hpc/reframe pull request #2534
Opened 2022-06-08 15:59 UTC by ekouts

One other thing we have talked about and would make sense to do in this PR is to expose `SLEEP_MIN`, `SLEEP_MAX` and `SLEEP_INC_RATE` in the configuration. It would be better to do it by partition but it would require more changes so maybe it's better to open an issue and do it in the next sprint. What do you think @vkarak ?

Fixes #2531.

2022-06-09 11:39 UTC, vkarak requested changes

2022-06-09 14:28 UTC, vkarak requested changes
Still just a couple of minor changes.

2022-06-09 14:28 UTC, vkarak commented on reframe/frontend/executors/policies.py
>              self._t_init = time.time()
I think that this should also go in `snooze()`, shouldn't it?

2022-06-09 14:28 UTC, vkarak commented on reframe/frontend/executors/policies.py
> +
Remove this line.

2022-06-09 14:56 UTC, vkarak commented
I tested also with the example in #2531 and it seems to work correctly now.

2022-06-10 08:01 UTC, ekouts commented
@jenkins-cscs retry all

2022-06-10 13:27 UTC, merged