Bump version of `requests` in `requirements.txt`
reframe-hpc/reframe pull request #2579
Opened 2022-08-26 10:27 UTC by giordano

This makes `requests` compatible with `chardet` v5: https://github.com/psf/requests/pull/6179

2022-08-26 10:29 UTC, giordano commented
But `chardet` 5 removed support for Python 3.6: https://github.com/chardet/chardet/releases/tag/5.0.0.  Sigh

2022-08-29 07:07 UTC, teojgo requested changes

2022-08-29 07:07 UTC, teojgo commented on requirements.txt
> +requests==2.28.1
```suggestion
requests==2.27.1; python_version == '3.6'
requests==2.28.1; python_version >= '3.7'
```

2022-08-29 09:40 UTC, teojgo commented
Ok to test

2022-08-29 09:58 UTC, vkarak approved these changes

2022-08-29 10:11 UTC, teojgo commented
@jenkins-cscs retry daint

2022-08-29 10:31 UTC, merged