[doc] Update link in codecov badge
reframe-hpc/reframe pull request #2708
Opened 2022-12-09 21:18 UTC by vkarak

I have reconnected codecov to this repo.

2022-12-12 07:54 UTC, teojgo requested changes

2022-12-12 07:54 UTC, teojgo commented on README.md
> +[![codecov](https://codecov.io/gh/reframe-hpc/reframe/branch/master/graph/badge.svg?token=9lpUzjKnaE)](https://codecov.io/gh/reframe-hpc/reframe)<br/>
Remove the token part.

2022-12-13 12:33 UTC, victorusu approved these changes
`lgtm`

2022-12-14 09:05 UTC, teojgo approved these changes

2022-12-14 09:20 UTC, merged