[bugfix] Fix listing on non-fixture dependencies
reframe-hpc/reframe pull request #2798
Opened 2023-02-22 14:27 UTC by teojgo

2023-02-22 17:33 UTC, vkarak commented
@teojgo Can you explain a bit what problem this PR solves?

2023-02-22 22:07 UTC, vkarak requested changes
Perhaps we should add a small cli test that you list test with dependencies, e.g., `./bin/reframe -c unittests/resources/checks_unlisted/deps_complex.py -l`

2023-02-23 09:01 UTC, teojgo commented
> @teojgo Can you explain a bit what problem this PR solves?

It fixes the problem where during listing, ReFrame tries to access fixture data even for non fixture tests.

2023-02-23 12:14 UTC, vkarak approved these changes

2023-02-23 12:30 UTC, merged