[doc] Provide further documentation about the `pipeline_timeout` attribute
reframe-hpc/reframe pull request #2816
Opened 2023-03-03 10:52 UTC by ekouts

Closes #2729 .

2023-03-03 19:24 UTC, vkarak requested changes

2023-03-03 19:24 UTC, vkarak commented on docs/pipeline.rst
> +Raising the throughput of jobs in the asynchronous policy
What about this as a title?

```suggestion
Tweaking the throughput and interactivity of test jobs in the asynchronous execution policy
```

2023-03-11 21:34 UTC, vkarak approved these changes

2023-03-11 21:58 UTC, vkarak commented
@jenkins-cscs retry all

2023-03-13 07:42 UTC, ekouts commented
@jenkins-cscs retry all

2023-03-13 08:37 UTC, merged