Allow to pass CI options for --ci-generate
reframe-hpc/reframe pull request #2833
Opened 2023-03-17 14:47 UTC by donion74

2023-03-17 14:55 UTC, donion74 commented
@jenkins-cscs Yes, I just updated the description.

2023-03-28 22:00 UTC, vkarak requested changes
Hi @donion74, thanks for the  PR!

I like the idea as it's simple, yet powerful. I think it essentially addresses what #2420 tries to do. @mahendrapaipuri Wdyt? Would that feature work for your case as well?

Other than that we'd need a unit test or expand the existing one in `test_ci.py` that basically exercises also this feature and a bit of fine tuning of the docs as this is not about adding "options" to the CI: users can essentially extend per test basis the generated child pipeline.

2023-03-29 07:58 UTC, mahendrapaipuri commented
@donion74 @vkarak I think it should work in my case as well. From what I see we can arbitrary configure the child pipeline within each "test", which was exactly what we were looking for. I really like this PR as it is a very simple and efficient solution.

@donion74 What happens if we want to configure directives that are explicitly generated by current CI code? For instance, ReFrame already emits [artifacts](https://github.com/reframe-hpc/reframe/blob/9de010f946e49546e4c34e6b08349ffdef03b98d/reframe/frontend/ci.py#L68-L69) to include the report file. If user wants to add more artifacts to it, with this PR, the user can set `ci_options` as

```
ci_options = {"artifacts": {"paths": ['/path1/to/save', '/path2/to/save']}}
```

which will end up generating a YAML file as follows in your example:

```
HelloModified:
  stage: rfm-stage-0
  script:
  - reframe --prefix=rfm-stage/${CI_COMMIT_SHORT_SHA}  -c /builds/latticeqcd/reframe-debug  --report-file=HelloModified-report.json  --report-junit=HelloModified-report.xml  -n '^HelloModified$' -r
  artifacts:
    paths:
    - HelloModified-report.json
  needs: []
  artifacts:
   paths:
     - /path1/to/save
     - /path2/to/save
```
So, the question is if the GitLab CI parser (in future if other CI engines will be supported, their parsers as well) is smart enough to merge them? Could you maybe do a quick test?

2023-03-29 14:05 UTC, donion74 commented on reframe/core/pipeline.py
> +    #: .. versionadded:: ??
Added it.

2023-03-29 14:06 UTC, donion74 commented on reframe/core/pipeline.py
> +                          value={}, loggable=True)
- removed loggable option.
- renamed it `ci_extras`.
- added the `gitlab` key.

2023-03-29 14:09 UTC, donion74 commented
@mahendrapaipuri Good point. If I try to reproduce your suggestions, the `artifacts` key is overwritten:

```
    ci_extras['gitlab'] = {**ci_extras['gitlab'], 
        "rules": [{"changes": ["src/hello.c"]}],
        'artifacts': {"paths": ['pipeline.yml', '.gitlab-ci.yml']}}
```
produces this pipeline:

```
HelloModified:
  stage: rfm-stage-0
  script:
  - reframe --prefix=rfm-stage/${CI_COMMIT_SHORT_SHA} -C /home/anian/phd/2-openqxd/tests/config//settings.py -c . -R --report-file=HelloModified-report.json  --report-junit=HelloModified-report.xml  -n '^HelloModified$' -r
  artifacts:
    paths:
    - pipeline.yml
    - .gitlab-ci.yml
  needs: []
  rules:
  - changes:
    - src/hello.c
```

I guess this is related to https://stackoverflow.com/q/14902299, and could be solved by the suggestion https://stackoverflow.com/a/61416215.

2023-03-29 14:10 UTC, donion74 commented
I updated the example git repo. Here are two pipelines that demonstrate the use of `changes`:
- https://gitlab.com/latticeqcd/reframe-debug/-/pipelines/821682420
- https://gitlab.com/latticeqcd/reframe-debug/-/pipelines/821685043

2023-03-29 18:03 UTC, mahendrapaipuri commented
Thanks @donion74 for the tests. So, if Gitlab CI is not merging them, we need to do it within ReFrame. So, currently ReFrame is emitting pipelines using directives `stage`, `script`, `artifacts` and `needs`.

- `stage` and `needs` are important for dependency resolution. So, if user defined `ci_extras` have these directives we need to ignore them 
- Document clearly that users need to use `before_script` and `after_script` for executing auxillary commands within a job. If user still passes `script` directive within `ci_extras`, we need to ignore it as we do not know whether to execute them before or after ReFrame job. A warning would be nice to have when this case arises.
- `artifacts` need to be merged.

I think this should do nicely to configure CI pipelines. What do you think @vkarak?

2023-04-03 19:43 UTC, vkarak commented
@mahendrapaipuri I agree with your suggestion. For `needs`, `stage` and `script` we need to issue an error I think and if the user passes `script` specifically, we should ask her to set either the `before_script` or `after_script` instead. `artifacts` should indeed be merged, but we should not bother implementing a generic JSON object merger but rather a specific one for the artifacts; reframe knows exactly what it emits for artifacts, so it can combine it with the user's artifacts accordingly.

2023-04-03 22:34 UTC, vkarak approved these changes
I updated the PR implementing the restrictions we just discussed and add also unit tests. Now lgtm. @donion74 @mahendrapaipuri If you confirm that it works for your use cases, then we can merge this PR.

2023-04-04 09:13 UTC, mahendrapaipuri commented
@vkarak Cheers @vkarak!! Yes, this would work for my cases and this PR is quite handy. Cheers @donion74 !!

2023-04-04 10:33 UTC, donion74 commented
Thanks for implementing the changes @vkarak , my pipeline still works as intended: https://gitlab.com/latticeqcd/reframe-debug/-/pipelines/827286511

The only downside I notice is that subsequent tests overwrite the variable `ci_extras`:
See the test [hello1.py](https://gitlab.com/latticeqcd/reframe-debug/-/blob/example/hello1.py), and the corresponding [pipeline](https://gitlab.com/latticeqcd/reframe-debug/-/pipelines/827454922), where I print the content of `ci_extras` in [line 43](https://gitlab.com/latticeqcd/reframe-debug/-/jobs/4057630126) and [line 43](https://gitlab.com/latticeqcd/reframe-debug/-/jobs/4057630127).

2023-04-04 13:40 UTC, mahendrapaipuri commented
@vkarak I managed to find the problem but not sure about the solution. Lets take a simplified test case:

```
@rfm.simple_test
class HelloArtifacts(rfm.RegressionTest):
    """only runs in merge requests and stores additional artifacts"""
    valid_systems = ['*']
    valid_prog_environs = ['*']
    sourcepath = 'hello.c'
    ci_extras['gitlab'] = {"rules": [{"if": "$CI_MERGE_REQUEST_ID"}],
                           'artifacts': {"paths": ['.gitlab-ci.yml']}}

    @sanity_function
    def assert_hello(self):
        print(self.ci_extras['gitlab'])
        return sn.assert_found(r'Hello, World\!', self.stdout)

@rfm.simple_test
class Simple(rfm.RegressionTest):
    """always runs"""
    valid_systems = ['*']
    valid_prog_environs = ['*']
    sourcepath = 'hello.c'
    desc = 'Simple'

    @sanity_function
    def assert_true(self):
        print(self.ci_extras)
        return True
```

This would produce a `pipeline.yml` as follows:

```
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - rfm-stage/${CI_COMMIT_SHORT_SHA}
stages:
- rfm-stage-0
Simple:
  stage: rfm-stage-0
  script:
  - reframe --prefix=rfm-stage/${CI_COMMIT_SHORT_SHA}  -c .  --report-file=Simple-report.json  --report-junit=Simple-report.xml -vvvvv -n '^Simple$' -r
  artifacts:
    paths:
    - Simple-report.json
    - .gitlab-ci.yml
  needs: []
  rules:
  - if: $CI_MERGE_REQUEST_ID
HelloArtifacts:
  stage: rfm-stage-0
  script:
  - reframe --prefix=rfm-stage/${CI_COMMIT_SHORT_SHA}  -c .  --report-file=HelloArtifacts-report.json  --report-junit=HelloArtifacts-report.xml -vvvvv -n '^HelloArtifacts$' -r
  artifacts:
    paths:
    - HelloArtifacts-report.json
    - .gitlab-ci.yml
  needs: []
  rules:
  - if: $CI_MERGE_REQUEST_ID
```
This is the buggy behaviour where `ci_extras` in `Simple` test are being populated from `HelloArtifacts`. However, if we change the way we set `ci_extras` to

```
 ci_extras = {''gitlab'': {"rules": [{"if": "$CI_MERGE_REQUEST_ID"}],
                           'artifacts': {"paths": ['.gitlab-ci.yml']}}}
```
we get correct behaviour giving us following `pipeline.yml`

```
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - rfm-stage/${CI_COMMIT_SHORT_SHA}
stages:
- rfm-stage-0
Simple:
  stage: rfm-stage-0
  script:
  - reframe --prefix=rfm-stage/${CI_COMMIT_SHORT_SHA}  -c .  --report-file=Simple-report.json  --report-junit=Simple-report.xml -vvvvv -n '^Simple$' -r
  artifacts:
    paths:
    - Simple-report.json
  needs: []
HelloArtifacts:
  stage: rfm-stage-0
  script:
  - reframe --prefix=rfm-stage/${CI_COMMIT_SHORT_SHA}  -c .  --report-file=HelloArtifacts-report.json  --report-junit=HelloArtifacts-report.xml -vvvvv -n '^HelloArtifacts$' -r
  artifacts:
    paths:
    - HelloArtifacts-report.json
    - .gitlab-ci.yml
  needs: []
  rules:
  - if: $CI_MERGE_REQUEST_ID
```
@vkarak , I hope that can give you an idea where to look at!!

2023-04-04 13:42 UTC, mahendrapaipuri commented on reframe/core/pipeline.py
> +    #: ci_options = {"only": {"changes": ["backend/*", "src/main.c"]}
In the example, it has to be `ci_extras` and dict must have `gitlab` key

2023-04-04 22:17 UTC, vkarak commented
I accidentally deleted my previous comment. If you instead set the `ci_extras` completely and not just the `'gitlab'` element, it should work. I am still investigating why this is happening and whether it is a corner case bug of the variables mechanism. I have fixed the PR to avoid this from happening by setting the default to `None`.

2023-04-04 22:51 UTC, vkarak commented
It is indeed a bug introduced in 4.0. See #2848. I will revert this PR's implementation using `{}` as the default value and @donion74 meanwhile update your tests to set the `ci_extras` as a whole until this bug is fixed.

2023-04-05 08:20 UTC, mahendrapaipuri commented
@vkarak @donion74 Seems like this regression is coming from this [commit](https://github.com/reframe-hpc/reframe/commit/d01138163e6ab5093827d9807f890435ad629b26). In the CI tests, we are explicitly setting the `--report-file` with relative path. The [basedir](https://github.com/reframe-hpc/reframe/blob/6e22addc096cb61640baaa8d9b8851c4975beda3/reframe/frontend/cli.py#L1339-L1344) is being calculated on relative path and wrapping it inside `os.path.abspath` should fix the problem.

2023-04-05 08:24 UTC, vkarak commented
@mahendrapaipuri Good catch, would you mind opening an issue? The `--report-file` should work with relative paths...

2023-04-05 08:32 UTC, mahendrapaipuri commented
@vkarak Issue #2849

2023-04-05 08:41 UTC, mahendrapaipuri commented
@vkarak @donion74 I was meaning to ask you if it is worth to include this new `ci_extras` in the ReFrame config file. So, instead of setting a default value within the class, we get it from the config file. 

The use case is that users can define a global CI config in the ReFrame config and override it for specific tests within the test. This is especially useful for users who wish to use same CI config for all tests as they will not need to set the config for "each" test.

2023-04-05 09:26 UTC, donion74 commented
This would be very useful. The initial reason I came up with that was to run the Gitlab CI only in merge request pipelines, so I would need to add the same 
```
  rules:
  - if: $CI_MERGE_REQUEST_ID
 ```
in all the tests. Your idea would avoid duplicate code.

2023-04-05 10:02 UTC, vkarak commented
@mahendrapaipuri I suggest opening an issue about that. There is also an old one that requests essentially this for any test variable #1500.

2023-04-05 21:14 UTC, merged