[feat] Add support for repeated testing through two new options: `--reruns` and `--duration`
reframe-hpc/reframe pull request #2839
Opened 2023-03-30 22:34 UTC by vkarak

This PR introduces the following two options that are meant to allow users to use reframe for stress testing a target system:

- The `--reruns=N` option will rerun the same test suite N times (N+1 total runs).
- The `--duration=TIMEOUT` option will run the same test suite repeatedly until `TIMEOUT` expires.

Compared to the similar `--max-retries` option that reruns the failed tests, these options will report statistics as well as failures from _all_ runs.

Closes #619.

@brandongc FYI

#### Todos

- [ ] Update the docs

2023-03-30 22:36 UTC, vkarak commented
ok to test

2023-03-30 22:43 UTC, teojgo commented
Ok to test

2023-04-05 07:32 UTC, ekouts requested changes
Overall it looks good, if you fix the very small comment I made I will approve.

2023-04-05 07:32 UTC, ekouts commented on reframe/frontend/executors/__init__.py
> +        '''Called when a RegressionTask has failed.'''
```suggestion
        '''Called when a RegressionTask has aborted.'''
```
Maybe you meant to write aborted here?

2023-04-06 07:26 UTC, ekouts approved these changes

2023-04-06 08:29 UTC, teojgo approved these changes

2023-04-06 08:49 UTC, merged