HTTPJSONHandler http POST customisable header #2850
reframe-hpc/reframe pull request #2854
Opened 2023-04-07 13:41 UTC by Lewih

I tested this with ncat and a small config file as 

```python
site_configuration = {
    'logging': [
        {
        'handlers_perflog': [

            {
            'type': 'httpjson',
            'url': 'http://localhost:12345',
            'level': 'info',
            'extras': {
                'facility': 'reframe',
                'data-version': '1.0'
            },
            'debug': False,
            'extra_headers': {
               'ApiKey': 'test'
            }
            }
            ]
        }
    ]
}
```
This solves #2850.

Should we implement a test ?

2023-04-07 13:50 UTC, teojgo requested changes
You would need to add this to the configuration schema as well.

2023-04-07 13:58 UTC, Lewih commented
> You would need to add this to the configuration schema as well.

gonna add it as ```"extra_headers": {"type": "object"},```

2023-04-07 14:02 UTC, Lewih commented
Documentation should be updated as well

2023-04-11 09:43 UTC, Lewih commented
@teojgo , The PR now follows the community guidelines and the schema has been updated.

As far as I have seen, no test is included for `extras` and the others entries of `httpjson` handler. I would postpone a more complete test implementation for the handler for another PR.

2023-04-11 09:46 UTC, teojgo commented
> @teojgo , The PR now follows the community guidelines and the schema has been updated.
> 
> As far as I have seen, no test is included for `extras` and the others entries of `httpjson` handler. I would postpone a more complete test implementation for the handler in another PR.

@Lewih Thanks for the PR and the update. Yes, we don't have any testing for the handler at the moment but suggestions are always welcome.

2023-04-11 09:46 UTC, teojgo approved these changes

2023-04-11 14:36 UTC, Lewih commented
> @Lewih Thanks for the PR and the update. Yes, we don't have any testing for the handler at the moment but suggestions are always welcome.

I opened an issue #2858 in order to track this.

2023-04-11 20:35 UTC, Lewih commented
Synched with upstream branch in order to re-run the test to make sure nothing breaks, then PR should be able to merge.

2023-04-14 22:43 UTC, vkarak approved these changes
Lgtm; I just did a couple of minor style enhancements.

2023-04-14 22:43 UTC, vkarak commented on docs/config_reference.rst
> +   A set of optional key/value pairs to be sent as HTTP message headers(e.g. API keys).
```suggestion
   A set of optional key/value pairs to be sent as HTTP message headers (e.g. API keys).
```

2023-04-14 22:43 UTC, vkarak commented on reframe/core/logging.py
> +    return HTTPJSONHandler(url, extras, ignore_keys, json_formatter, extra_headers, debug)
```suggestion
    return HTTPJSONHandler(url, extras, ignore_keys, json_formatter,
                           extra_headers, debug)
```

2023-04-14 22:53 UTC, vkarak commented
We'll merge this after #2861 is addressed, which has broken our CI.

2023-04-20 07:58 UTC, merged