Check exit status of PBS Pro jobs
reframe-hpc/reframe pull request #2993
Opened 2023-09-11 17:45 UTC by giordano

This is a start to address #2936.  It doesn't quite work as desired at the moment, because I don't know what to do exactly with the exit status, how do I use it to make ReFrame error if the job failed?

2023-09-11 21:06 UTC, vkarak commented
I would suggest re-opening this as a bugfix against `master`.

2023-09-12 13:36 UTC, giordano commented
Changed target branch to `master`.

2023-09-12 14:48 UTC, giordano commented
Ok, I think this is ready for review: before it wasn't working because I made a mistake in the regexp pattern (didn't use the `re.MULTILINE` flag and so `^` wasn't matching the beginning of a line within the whole string), after fixing that the build job is failing as expected.  It looks like that setting `job._exitcode` is enough for ReFrame to handle this correctly.

2023-09-12 16:05 UTC, giordano commented
Uhm, I think now this fails also when jobs are successful, but I don't understand why :confused:

2023-09-16 10:24 UTC, vkarak commented
ok to test

2023-09-16 10:50 UTC, vkarak requested changes

2023-09-16 10:50 UTC, vkarak commented on reframe/core/schedulers/pbs.py
> +                        job._exitcode = int(exit_status_match.group('exit_status'))
I would not use the `if` here but rather let inheritance take care of it.

```python
job._exitcode = self._query_exit_code(job.jobid)
```

Where each of the PBS-based backends implements `_query_exit_code()` accordingly. The `torque` backend will simply return `None`.

2023-09-22 22:08 UTC, vkarak approved these changes

2023-09-22 22:09 UTC, vkarak commented
@giordano I updated the PR based on the last comments. Can you give it a try and check if anything is broken so that we can merge it?

2023-09-26 07:24 UTC, teojgo approved these changes

2023-09-29 21:30 UTC, merged

2023-10-05 12:11 UTC, giordano commented
Sorry, I just managed to run the test with the latest version of `develop` (which includes the latest changes in this PR), and I can confirm that the exit status of the build job is handled correctly in PBS Pro.  Thanks!