Add sched_bind_options in env config
reframe-hpc/reframe pull request #3078
Opened 2023-12-12 11:00 UTC by ekouts

Closes #2991.

I am a bit confused by a comment from @vkarak

> Just to be clear, the above syntax is proposed for the partition definition.

Why would these options be defines in the partition?

2023-12-12 11:00 UTC, pep8speaks commented
Hello @ekouts, Thank you for submitting the Pull Request!



* In the file [`reframe/core/pipeline.py`](https://github.com/reframe-hpc/reframe/blob/45348571aba245563229de9f6782d3c47881ee86/reframe/core/pipeline.py):

> [Line 1695:80](https://github.com/reframe-hpc/reframe/blob/45348571aba245563229de9f6782d3c47881ee86/reframe/core/pipeline.py#L1695): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)



Do see the ReFrame [Coding Style Guide](https://github.com/reframe-hpc/reframe/wiki/coding-style-guide)

2023-12-14 16:16 UTC, teojgo approved these changes

2023-12-19 20:45 UTC, vkarak requested changes
We would also need a unit test.

2023-12-19 20:45 UTC, vkarak commented on reframe/core/pipeline.py
> +                          ),
I would rather not mix it with `sched_access`. Instead, I would prepend it to the `sched_options` passed in `job_opts`.

2023-12-19 21:23 UTC, vkarak approved these changes

2023-12-20 09:08 UTC, vkarak commented
I was about to merge this, but read this and the original issue:

> Why would these options be defined in the partition?

@ekouts Yes, it was proposed to be in the `environs` because it's a partition's property how you should bind the environment and not the environment's. 

I'm removing it from 4.5 as we need to understand what's the best way to implement it.

2024-03-20 12:36 UTC, closed without merging