[feat] Introduce launcher modifiers replacing `LauncherWrapper`
reframe-hpc/reframe pull request #3114
Opened 2024-02-10 21:42 UTC by vkarak

This PR introduces two new variables in `JobLauncher`: `modifier` and `modifier_options`. These are combined and prepended to the emitted parallel launcher command. The use of `LauncherWrapper` is depreceted.

Closes #3100.

2024-02-15 09:52 UTC, teojgo requested changes

2024-02-15 09:52 UTC, teojgo commented on reframe/core/launchers/__init__.py
> +        user_deprecation_warning("'LauncherWrapper is deprected; "
```suggestion
        user_deprecation_warning("'LauncherWrapper is deprecated; "
```

2024-02-18 19:58 UTC, victorusu approved these changes
`lgtm`

2024-02-19 09:05 UTC, teojgo approved these changes

2024-02-19 21:32 UTC, merged