Support injection of scheduler options from an environment
reframe-hpc/reframe pull request #3152
Opened 2024-04-04 09:35 UTC by ekouts

This is a second attempt for this issue. I am missing the documentation + unittests but I would like first to agree on the api.

It would be very similar to the resources of the test. And the configuration would look like this.

```
site_configuration = {
    'systems': [
        {
            ...
            'partitions': [
                {
                    'resources': [
                        {
                            'name': 'switches',
                            'options': ['--switches={num_switches}']
                        },
                        {
                            'name': 'gres',
                            'options': ['--gres={gres}']
                        }
                    ],
                    'env_resources': [
                        {
                            'name': 'uenv',
                            'options': [
                                '--uenv-file={file}',
                                '--uenv-mount={mount}',
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    'environments': [
        {
            'name': 'myenv',
            'resources': {
                'uenv': {
                    'mount': 'one',
                    'file': 'two',
                }
            }
        }
    ]
}
```

That would translate to the following options in the job script:
```bash
#SBATCH --uenv-file=two
#SBATCH --uenv_mount=one
```

Closes #2991 .

2024-04-04 09:35 UTC, pep8speaks commented
Hello @ekouts, Thank you for submitting the Pull Request!





* In the file [`reframe/core/systems.py`](https://github.com/reframe-hpc/reframe/blob/e5a1aa630671810d1369d108119dff844b8acacc/reframe/core/systems.py):

> [Line 170:80](https://github.com/reframe-hpc/reframe/blob/e5a1aa630671810d1369d108119dff844b8acacc/reframe/core/systems.py#L170): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)

Do see the ReFrame [Coding Style Guide](https://github.com/reframe-hpc/reframe/wiki/coding-style-guide)

2024-04-11 08:28 UTC, teojgo requested changes

2024-04-11 08:28 UTC, teojgo commented on docs/config_reference.rst
> +  The name of this resources.
```suggestion
  The name of the resources.
```

2024-04-11 08:28 UTC, teojgo commented on docs/config_reference.rst
> +ReFrame allows you to define custom scheduler resources for each partition that you can then transparently access through the :attr:`~reframe.core.pipeline.RegressionTest.extra_resources` attribute o
```suggestion
ReFrame allows you to define custom scheduler resources for each partition/environment that can then be transparently accessed through the :attr:`~reframe.core.pipeline.RegressionTest.extra_resources` attribute of a regression test or the environment.
```

2024-04-11 08:28 UTC, teojgo commented on docs/config_reference.rst
> +   This is very similar to the :attr:`~config.systems.partitions.resources.options` parameter, but it is used to define resources that are specific to a programming environment.
```suggestion
   This is very similar to the :attr:`~config.systems.partitions.resources.options` parameter, but it is used to define resources specific to a programming environment.
```

2024-04-11 08:37 UTC, teojgo approved these changes

2024-04-13 20:47 UTC, vkarak requested changes
I think we should omit completely the `env_resources` and simply enable environments to use any of the scheduler resources. This would simplify the implementation and make also more sense at the partition level, as conceptually it doesn't make sense to separate the two types of resources.

2024-04-13 20:47 UTC, vkarak commented on reframe/core/environments.py
> +        '''The resources associated with this environment.
```suggestion
        '''The scheduler resources associated with this environment.
```

2024-04-18 22:42 UTC, vkarak requested changes
Just some minor style changes.

2024-04-18 22:42 UTC, vkarak commented on docs/config_reference.rst
> +ReFrame allows you to define custom scheduler resources for each partition/environment that can then be transparently accessed through the :attr:`~reframe.core.pipeline.RegressionTest.extra_resources
```suggestion
ReFrame allows you to define custom scheduler resources for each partition that can then be transparently accessed through the :attr:`~reframe.core.pipeline.RegressionTest.extra_resources` attribute of a test or from an environment.
```

2024-04-18 22:42 UTC, vkarak commented on docs/config_reference.rst
> +   This is similar to a regression test's :attr:`~reframe.core.pipeline.RegressionTest.extra_resources`.
```suggestion
   Scheduler resources associated with this environments.
   
   This is the equivalent of a test's :attr:`~reframe.core.pipeline.RegressionTest.extra_resources`.
```

2024-04-18 22:42 UTC, vkarak commented on unittests/resources/config/settings.py
> +                            ],
```suggestion
                            ]
```

2024-04-18 22:46 UTC, vkarak approved these changes

2024-04-19 06:08 UTC, ekouts commented
Thanks @vkarak for finishing the PR!

2024-04-19 06:08 UTC, merged