Update `archspec` and topology file call for CPU model name
reframe-hpc/reframe pull request #3185
Opened 2024-05-06 22:53 UTC by jack-morrison

This follows https://github.com/reframe-hpc/reframe/pull/3107 and https://github.com/reframe-hpc/reframe/pull/3132 to adopt the new function from [archspec v0.2.4](https://github.com/archspec/archspec/releases/tag/v0.2.4) returning a CPU brand string.

2024-05-06 22:56 UTC, victorusu commented
test this patch

2024-05-07 08:53 UTC, teojgo requested changes
The `setup.cfg` should be updated as well so that the wheel validation test passes. and the correct pypi package is produced.

2024-05-07 16:01 UTC, jack-morrison commented
> The `setup.cfg` should be updated as well so that the wheel validation test passes. and the correct pypi package is produced.

Done -- thanks for the pointer @teojgo 😃

2024-05-07 20:57 UTC, vkarak requested changes

2024-05-07 20:57 UTC, vkarak commented on setup.cfg
> +    archspec <= 0.2.4
```suggestion
    archspec >= 0.2.4
```

2024-05-07 21:07 UTC, jack-morrison commented on setup.cfg
> +    archspec <= 0.2.4
oops

2024-05-07 21:22 UTC, vkarak approved these changes

2024-05-07 21:44 UTC, merged