[feat] Add a perflog entry also when sanity fails
reframe-hpc/reframe pull request #3189
Opened 2024-05-13 17:38 UTC by vkarak

The idea is the same as exposed in the issue.
In case of sanity failures, we execute also the performance stage but in dry-run mode suppressing any non-aborting exception. To achieve so, we also extended the dry-run mode inside the performance stage to also generate the `perfvalues` which are required by the logging handlers for emitting the performance record.

In case of sanity failures, the performance values will be logged as `None`.

### Todos

- [ ] Add a `check_fail_reason` log format placeholder for allowing the fail reason to be also logged.

Closes #3186.

2024-05-13 17:38 UTC, pep8speaks commented
Hello @vkarak, Thank you for submitting the Pull Request!



* In the file [`reframe/core/pipeline.py`](https://github.com/reframe-hpc/reframe/blob/662c93e363b772879ca5c9f6978da9d3d3526fa3/reframe/core/pipeline.py):

> [Line 2302:33](https://github.com/reframe-hpc/reframe/blob/662c93e363b772879ca5c9f6978da9d3d3526fa3/reframe/core/pipeline.py#L2302): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent







* In the file [`unittests/test_cli.py`](https://github.com/reframe-hpc/reframe/blob/662c93e363b772879ca5c9f6978da9d3d3526fa3/unittests/test_cli.py):

> [Line 426:80](https://github.com/reframe-hpc/reframe/blob/662c93e363b772879ca5c9f6978da9d3d3526fa3/unittests/test_cli.py#L426): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)



Do see the ReFrame [Coding Style Guide](https://github.com/reframe-hpc/reframe/wiki/coding-style-guide)

2024-05-13 17:45 UTC, vkarak commented on reframe/core/pipeline.py
> +                raise PerformanceError(e) from None
This is simply indented out, as it does not need to be executed from the stage dir.

2024-05-13 17:46 UTC, vkarak commented on reframe/core/logging.py
> -
I removed this since it was unused.

2024-05-15 08:55 UTC, teojgo requested changes

2024-05-15 08:55 UTC, teojgo commented on unittests/test_policies.py
> +    logfile = (tmp_path / 'perflogs' / 'generic' / 'default' / '_X.log')
Remove the `()` here

2024-05-15 17:23 UTC, merged