Tutorial patch
reframe-hpc/reframe pull request #3208
Opened 2024-06-01 05:14 UTC by createyourpersonalaccount

Deals with #3198. Also corrects a mischaracterization of `builtin`; it
is not a partition, it is an environment.

2024-06-05 20:40 UTC, vkarak commented
Could you rebase your PR on master? Generally, bug fixes, docs and anything unrelated to new functionality goes into master (check the [Contribution guidelines](https://github.com/reframe-hpc/reframe/wiki/Contributing-to-ReFrame))

2024-06-05 21:12 UTC, vkarak requested changes

2024-06-05 21:12 UTC, vkarak commented on docs/tutorial.rst
> +This tells ReFrame that this test is valid only for environments that define the ``stream`` feature; the ``+`` prefix requests a feature. The syntax defined in :attr:`valid_prog_environs` allows for
```suggestion
This tells ReFrame that this test is valid only for environments that define the ``stream`` feature (the ``+`` prefix requests a feature; we will explain the syntax later in this section).
```

And then expand later in the bullet list that talks about features and extras (I can do that).

2024-06-06 11:23 UTC, createyourpersonalaccount commented on docs/tutorial.rst
> +        # ...
Oh okay, I thought it was invalid.

2024-06-06 11:23 UTC, createyourpersonalaccount commented
> Could you rebase your PR on master? Generally, bug fixes, docs and anything unrelated to new functionality goes into master (check the [Contribution guidelines](https://github.com/reframe-hpc/reframe/wiki/Contributing-to-ReFrame))

I assumed it went on development because you tagged it as ReFrame 4.7.

2024-06-06 11:37 UTC, vkarak commented
> I assumed it went on development because you tagged it as ReFrame 4.7.

Yeah, we don't use separate backlogs for patch releases.

2024-06-06 20:57 UTC, vkarak approved these changes

2024-06-06 21:07 UTC, merged